export const LOGGED_OUT_OF_NODRAFT = 'LOGGED_OUT_OF_NODRAFT';
export const OPEN_NODRAFT = 'OPEN_NODRAFT';
export const AUTH_CODE_RECEIVED = 'AUTH_CODE_RECEIVED';
export const OPEN_OPTIONS = 'OPEN_OPTIONS';

export const SAVE_TO_NODRAFT_REQUEST = 'SAVE_TO_NODRAFT_REQUEST';
export const SAVE_TO_NODRAFT_SUCCESS = 'SAVE_TO_NODRAFT_SUCCESS';
export const SAVE_TO_NODRAFT_FAILURE = 'SAVE_TO_NODRAFT_FAILURE';

export const USER_LOG_IN = 'USER_LOG_IN';
